/* ============================================================
   프로젝트 아카이브 데이터
   ------------------------------------------------------------
   이 파일만 수정하면 사이트 내용이 바뀝니다. (레이아웃/기능은 건드리지 않아도 됨)

   2026-09-09 — portfolio-text-review.md 기준으로 전체 워크 레퍼런스를 갱신했습니다.
   텍스트 파일에서 삭제된 프로젝트는 이 데이터에서도 삭제했습니다.
============================================================ */
const PROJECTS = [

  {
    company: 'DRILLTIES', companyLabel: 'DRILL TIES', year: 2026,
    title: 'LE SSERAFIM 〈PURE FLOWERS LIVE〉 Presented by Spotify',
    date: '2026.05.21',
    client: 'Spotify Korea · FIG',
    category: 'LIVE EVENT', venueEn: 'Seosomun Shrine History Museum', locationEn: 'Seoul, Korea',
    production: 'FIG',
    role: 'Show Direction · Creative Direction',
    desc: "르세라핌의 두 번째 정규 앨범인 'PUREFLOW' Pt.1 발매를 기념하여 스포티파이 프리미엄 유저를 대상으로 개최한 프라이빗 라이브 이벤트",
    tasks: ['프로그램 및 공연 구성 총괄', '현장 리허설 및 쇼 플로우 총괄', '출연진 및 파트너 커뮤니케이션'],
    image: 'https://storage.googleapis.com/pr-newsroom-wp/1/2026/06/HEADER-ONLY-2277683620-scaled.jpg',
  },

  {
    company: 'DRILLTIES', companyLabel: 'DRILL TIES', year: 2026,
    title: '〈겸손은힘들다〉 LIVE TOUR',
    date: '대전 03.14 · 대구 04.18 · 고양 04.25 · 부산 05.02 · 전주 05.09 · 광주 05.16 외',
    client: 'Live Land Co., Ltd.',
    category: 'LIVE CONCERT & TOUR', venueEn: 'KINTEX · EXCO · BEXCO · Korea National Culture and Arts Center, etc.', locationEn: 'Daejeon · Daegu · Goyang · Busan · Jeonju · Gwangju, Korea',
    production: 'Drill ties',
    role: 'Show Direction · Creative Direction · Project Management',
    desc: '전국 투어 토크 콘서트 연출 및 진행',
    tasks: ['프로그램 및 공연 구성 총괄', '현장 리허설 및 쇼 플로우 총괄', '출연진 섭외 및 계약, 파트너 커뮤니케이션', '투어 정산 및 비용 관리'],
    localImage: 'images/projects/2026-gyeomson-live-tour.jpg',
    image: 'https://tkfile.yes24.com/upload2/PerfBlog/202601/20260129/20260129-56961.jpg',
  },

  {
    company: 'DRILLTIES', companyLabel: 'DRILL TIES', year: 2026,
    title: 'K-Dream Stage: All India K-Pop Grand Championship 2026',
    date: '2026.04.20',
    client: 'Korean Cultural Centre India · MAC Communication',
    category: 'LIVE EVENT', venueEn: 'Yashobhoomi Indoor Stadium', locationEn: 'New Delhi, India',
    production: 'MAC Communication',
    role: 'Show Direction · Creative Direction · Project Management',
    desc: '인도 전역의 K-POP 경연을 결산하는 대규모 챔피언십으로, 현지 팬과 한류 콘텐츠를 연결한 문화교류 프로젝트',
    tasks: ['경연 진행 및 심사, 시상식 연출 총괄', '현지 업체 어레인지 및 커뮤니케이션', '출연자 계약·비자 수속, 의전 등 행사 진행 일체', '행사 정산 및 비용 관리'],
    image: 'https://m.economictimes.com/thumb/msid-130335829%2Cwidth-1200%2Cheight-1200%2Cresizemode-4%2Cimgsize-97078/img_4833-.jpg',
  },

  {
    company: 'DRILLTIES', companyLabel: 'DRILL TIES', year: 2026,
    title: 'OMIYAGE+ 일본 프리미엄 오미야게 팝업 이벤트',
    date: '2026.01',
    client: 'Japan Omiyage Association · Irae Company',
    category: 'POP-UP', venueEn: 'IFC Mall', locationEn: 'Seoul, Korea',
    production: '이래컴퍼니(Irae Company)',
    role: 'Creative Direction',
    desc: '일본 각 지역을 대표하는 디저트 브랜드 4곳이 일본 여행의 오미야게 쇼핑 경험을 현지처럼 즐길 수 있도록 기획한 팝업 이벤트',
    tasks: ['팝업 컨셉 및 프로그램 개발', '팝업 공간 디자인 및 운영 계획 수립', '팝업 제작 및 설치, 운영 일체'],
    image: 'https://pimg.mk.co.kr/news/cms/202601/30/news-p.v1.20260130.693a58896e144a038a31987af0cab238_R.jpg',
  },

  {
    company: 'DRILLTIES', companyLabel: 'DRILL TIES', year: 2026,
    title: '故 신영복 선생 서거 10주기 추모식',
    date: '2026.01.15',
    client: 'Sungkonghoe University · Deobureosup · Dolbegae Publishers',
    category: 'Memorial', venueEn: "Sungkonghoe University St. Michael's Chapel", locationEn: 'Seoul, Korea',
    production: '성공회대',
    role: 'Technical Direction, Event management',
    desc: '故 신영복 선생 서거 10주기 추모식',
    tasks: ['추모식 진행 총괄', '출연진 및 파트너 커뮤니케이션'],
    localImage: 'images/projects/2026-shin-young-bok-memorial.jpg',
  },

  {
    company: 'DRILLTIES', companyLabel: 'DRILL TIES', year: 2025,
    title: "'12·3 비상계엄 해제 1주년' 기념행사 〈빛의 민주주의, 꺼지지 않는 기억〉",
    date: '2025.12.03',
    client: 'National Assembly · MEGAON',
    category: 'Official CEREMONY', venueEn: 'National Assembly Central Lawn Square', locationEn: 'Seoul, Korea',
    production: '티클모아',
    role: 'Creative Direction · Project Management',
    desc: '역사적 기억을 건축 외벽과 미디어 콘텐츠로 확장한 미디어파사드 프로젝트',
    tasks: ['미디어파사드 콘텐츠 컨셉 및 제작 총괄', '현장 리허설 및 이벤트 진행 총괄', '운영 계획 및 관계자, 협력사 커뮤니케이션'],
    localImage: 'images/projects/2025-december-3-democracy.jpg',
  },

  {
    company: 'DRILLTIES', companyLabel: 'DRILL TIES', year: 2025,
    title: 'APEC 2025 KOREA 공식 환영식',
    date: '2025.10.31~11.01',
    client: 'APEC 2025 KOREA · ezPMP',
    category: 'Official CEREMONY', venueEn: 'Silla History & Culture Center', locationEn: 'Gyeongju, Korea',
    production: 'ezPMP',
    role: 'Creative Direction · Project Management',
    desc: '공식 환영식 진행 및 배우자 프로그램 공간 조성',
    tasks: ['공식 행사 진행 지원', '행사장 공간 디자인 및 가구·집기 조성'],
    image: 'https://jinju.museum.go.kr/_prog/download/?func_gbn_cd=popup_zone&mng_no=411',
  },

  {
    company: 'DRILLTIES', companyLabel: 'DRILL TIES', year: 2025,
    title: '광복 80년 전야제 〈대한이 살았다!〉',
    date: '2025.08.14',
    client: 'National Assembly · Ministry of Patriots and Veterans Affairs · Korea Liberation Association',
    category: 'Official CEREMONY', venueEn: 'National Assembly Central Lawn Square', locationEn: 'Seoul, Korea',
    production: '티클모아',
    role: 'Show Direction · Creative Direction · Project Management',
    desc: '광복 80년의 메시지를 대중음악, 미디어파사드와 드론쇼로 확장한 대규모 국가 기념 문화행사',
    tasks: ['프로그램 및 공연 구성 총괄', '현장 리허설 및 쇼 플로우 총괄', '출연진 및 관계자, 파트너 커뮤니케이션'],
    localImage: 'images/projects/2025-liberation-80-eve.jpg',
    image: 'https://korea815.go.kr/images/site/kor/sub/event1_img06.jpg',
  },

  {
    company: 'DRILLTIES', companyLabel: 'DRILL TIES', year: 2025,
    title: '더파워풀 The Powerful',
    date: '2025.06.27~06.29',
    client: 'BTC COMMUNICATION',
    category: 'LIVE CONCERT', venueEn: 'INSPIRE Arena', locationEn: 'Yeongjongdo, Incheon, Korea',
    production: '티클모아',
    role: 'Creative Planning · Production Support',
    desc: '음악과 무대, 관객을 대형 아레나 스케일로 연결한 공연 프로젝트',
    tasks: ['공연 콘텐츠 기획 및 출연진 섭외'],
    localImage: 'images/projects/2025-the-powerful.gif',
  },

  {
    company: 'DRILLTIES', companyLabel: 'DRILL TIES', year: 2023,
    title: '2023 HWANG MIN HYUN MINI CONCERT 〈UNVEIL〉 — ASIA TOUR',
    client: 'PLEDIS Entertainment · HYBE',
    category: 'LIVE CONCERT & TOUR', venueEn: 'Kyung Hee University Grand Peace Palace + 6 Asian cities', locationEn: 'Seoul · Taipei · Jakarta · Macau · Bangkok · Manila · Tokyo',
    role: 'Show Direction · Creative Direction',
    desc: '황민현 미니콘서트 서울 공연 및 아시아 투어 연출',
    tasks: ['공연 컨셉 개발 및 구성 총괄', '쇼 플로우 연출 및 현장 리허설 진행', '출연진 및 현지 파트너 커뮤니케이션'],
    image: 'https://image.toast.com/aaaaab/ticketlink/TKL_1/hwang_pst_0628.jpg',
  },

  {
    company: 'DRILLTIES', companyLabel: 'DRILL TIES', year: 2024,
    displayYear: '2023-2024',
    title: '2023 BAEKHO MINI CONCERT 〈BAEKHoney DAY〉 - ASIA TOUR',
    client: 'PLEDIS Entertainment · HYBE',
    category: 'LIVE CONCERT & TOUR', venueEn: 'YES24 Live Hall +2 Asian cities', locationEn: 'Seoul · Taipei · Bangkok',
    role: 'Show Direction · Creative Direction',
    desc: '백호 미니콘서트 서울 공연 및 아시아 투어 연출',
    tasks: ['프로그램 및 공연 구성 총괄', '쇼 플로우 연출 및 현장 리허설 진행', '출연진 및 현지 파트너 커뮤니케이션'],
    image: 'https://stkfile.yes24.com/upload2/PerfBlog/202304/20230412/20230412-45489_1.jpg',
  },

  {
    company: 'DRILLTIES', companyLabel: 'DRILL TIES', year: 2020,
    title: '6·25전쟁 제70주년 기념식 〈영웅에게〉',
    client: 'Ministry of National Defense · Ministry of Patriots and Veterans Affairs',
    category: 'OFFICIAL CEREMONY', venueEn: 'Seoul Air Base', locationEn: 'Seongnam, Korea',
    role: 'Show Direction · Creative Direction',
    desc: '전사자 147위의 귀환을 국가 의전과 추모의 메시지로 구성한 6·25전쟁 70주년 행사',
    tasks: ['프로그램 및 공연 구성', '쇼 플로우 연출 및 현장 리허설 진행', '출연진 및 파트너 커뮤니케이션'],
    image: 'https://img.asiatoday.co.kr/file/2020y/06m/24d/2020062401002600900154831.jpg',
  },

  {
    company: 'DRILLTIES', companyLabel: 'DRILL TIES', year: 2019,
    title: 'AKMU 신규 앨범 청음회 〈가을밤의 항해〉',
    client: 'YG ENTERTAINMENT',
    category: 'LIVE EVENT', venueEn: '여의도한강공원 물빛무대', locationEn: 'Seoul, Korea',
    role: 'Show Direction · Project Management',
    desc: "악뮤(AKMU) 세 번째 정규앨범 '항해' 발매를 기념한 야외 청음회",
    tasks: ['쇼 플로우 연출 및 현장 리허설 진행', '출연진 및 파트너 커뮤니케이션'],
    localImage: 'images/projects/2019-akmu.jpg',
  },

  {
    company: 'DRILLTIES', companyLabel: 'DRILL TIES', year: 2019,
    title: '대통령 노르웨이 순방 계기 K팝 콘서트 & 한국 음악 콘서트 〈VOYAGE TO K-POP〉',
    client: 'Korean Cultural Center in Norway',
    category: 'LIVE CONCERT', venueEn: 'Sentrum Scene, Oslo Opera House', locationEn: 'Oslo, Norway',
    role: 'Show Direction · Creative Direction · Project Management',
    desc: '대통령 북유럽 순방 계기 문화 공연 프로그램',
    tasks: ['쇼 플로우 연출 및 현장 리허설 진행', '현지 업체 어레인지 및 커뮤니케이션', '출연자 계약·비자 수속, 의전 등 행사 진행 일체', '행사 정산 및 비용 관리'],
    localImage: 'images/projects/2019-voyage-to-kpop.jpg',
    image: 'https://0.soompi.io/wp-content/uploads/2019/06/12202602/monsta-x-2.jpg',
  },

  {
    company: 'DRILLTIES', companyLabel: 'DRILL TIES', year: 2019,
    title: '2019 정동하 콘서트 〈동하 읽어주는 남자〉 Vol.1',
    client: '',
    category: 'LIVE CONCERT', venueEn: 'LG Arts Center', locationEn: 'Seoul, Korea',
    role: 'Show Direction · Creative Direction',
    desc: '정동하 단독 콘서트',
    tasks: [],
    localImage: 'images/projects/2019-jung-dong-ha.jpg',
  },

  {
    company: 'DRILLTIES', companyLabel: 'DRILL TIES', year: 2018,
    title: '제70주년 국군의 날 국군 유해 봉환행사 ‘대한민국의 이름으로 당신을 기억하겠습니다’',
    client: 'Ministry of National Defense',
    category: 'OFFICIAL CEREMONY', venueEn: 'Seoul Air Base / War Memorial of Korea', locationEn: 'Seoul, Korea',
    role: 'Creative Direction',
    desc: '한미 공동감식을 통해 국군 전사자로 판정된 64위의 유해를 모시는 행사',
    tasks: [],
    image: 'https://www.korean-culture.org/CONTENTS/editImage/20181002174241902_1.jpg',
  },

  {
    company: 'DRILLTIES', companyLabel: 'DRILL TIES', year: 2018,
    title: '조코 위도도 인도네시아 대통령 국빈방한 - 국빈만찬',
    client: 'Cheong Wa Dae',
    category: 'OFFICIAL CEREMONY', venueEn: 'Cheongwadae (the Blue House)', locationEn: 'Seoul, Korea',
    role: 'Creative Direction · Project Management',
    desc: '인도네시아 대통령 국빈방한을 위한 공식 환영·만찬 프로그램',
    tasks: [],
    image: 'https://setkab.go.id/wp-content/uploads/2018/09/konpres-1.jpg',
  },

  {
    company: 'DRILLTIES', companyLabel: 'DRILL TIES', year: 2018,
    title: 'DMZ PEACE TRAIN MUSIC FESTIVAL 2018',
    client: 'Cheorwon County',
    category: 'FESTIVAL', venueEn: 'DMZ / Cheorwon', locationEn: 'Gangwon, Korea',
    role: 'Operation',
    desc: 'DMZ 철원에서 펼쳐지는 글로벌 뮤직 페스티벌',
    tasks: [],
    image: 'https://img.koreatimes.co.kr/upload/newsV2/images/201806/3520dac082db42eb955ff22080657b38.jpg',
  },

  {
    company: 'DRILLTIES', companyLabel: 'DRILL TIES', year: 2018,
    title: '에르도안 터키 대통령 국빈방문 - 국빈만찬',
    client: 'Cheong Wa Dae',
    category: 'OFFICIAL CEREMONY', venueEn: 'Cheongwadae (the Blue House)', locationEn: 'Seoul, Korea',
    role: 'Creative Direction, Project Management',
    desc: '터키 대통령 국빈방문을 위한 공식 환영·만찬 프로그램',
    tasks: [],
    image: 'https://img.khan.co.kr/news/2018/05/02/l_2018050201000258800017491.jpg',
  },

  {
    company: 'DRILLTIES', companyLabel: 'DRILL TIES', year: 2018,
    title: '남북평화 협력기원 남측예술단 평양공연 〈봄이 온다〉',
    client: 'Cheong Wa Dae · Ministry of Unification',
    category: 'LIVE CONCERT', venueEn: 'East Pyongyang Grand Theatre · Ryugyong Chung Ju-yung Gymnasium', locationEn: 'Pyongyang, North Korea',
    role: 'Show Direction · Creative Direction · Project Management',
    desc: '남북정상회담의 문화적 교류를 상징한 남측예술단 평양 공연',
    tasks: [],
    localImage: 'images/projects/2018-spring-is-coming.jpg',
    image: 'https://www.korean-culture.org/CONTENTS/editImage/20180402173214530_1.jpg',
  },

  {
    company: 'DRILLTIES', companyLabel: 'DRILL TIES', year: 2017,
    title: '트럼프 미국 대통령 초청 국빈만찬',
    client: 'Cheong Wa Dae',
    category: 'OFFICIAL CEREMONY', venueEn: 'Yeongbingwan State Guest House, Cheongwadae', locationEn: 'Seoul, Korea',
    role: 'Creative Direction · Project Management',
    desc: '미국 대통령 국빈방문을 위한 공식 환영·만찬 프로그램',
    tasks: [],
    image: 'https://img1.newsis.com/2017/11/07/NISI20171107_0013541936_web.jpg',
  },

  {
    company: 'DRILLTIES', companyLabel: 'DRILL TIES', year: 2017,
    title: '올댓뮤직X인디스땅스2017',
    client: 'Gyeonggi Content Agency',
    category: 'BAND COMPETITION PROJECT', venueEn: 'Undisclosed', locationEn: 'Korea',
    role: 'Creative Direction · Project Management',
    desc: '인디 뮤지션 발굴을 위한 오디션 프로그램 운영 및 라이브 이벤트 진행',
    tasks: [],
    localImage: 'images/projects/2017-indistance.jpg',
  },

  {
    company: 'FIG', companyLabel: 'FIG', year: 2025,
    title: '2025 BTS FESTA',
    date: '2025.06.13~06.14',
    client: 'BIGHIT MUSIC · HYBE · FIG',
    category: 'LIVE EXPERIENCE · EXHIBITION', venueEn: 'KINTEX Exhibition Hall 2, Halls 9-10', locationEn: 'Goyang, Korea',
    production: 'FIG',
    role: 'Creative Direction · Project Management',
    desc: 'BTS 데뷔 12주년을 기념한 공식 팬 이벤트',
    tasks: ['프로그램 및 공연 구성 총괄', '공간 디자인 및 제작, 설치 총괄', '운영 계획 및 관계자, 협력사 커뮤니케이션', '행사 정산 및 예산 관리'],
    image: 'https://cf.creatrip.com/occasion/b0630cc20d658pe42deee498e0bd65e93gbj.jpeg',
  },

  {
    company: 'FIG', companyLabel: 'FIG', year: 2025,
    title: 'YouTube FanFest Korea 2025 — Live Show (Presented by U+)',
    date: '06.15',
    client: 'YOUTUBE KOREA · FIG',
    category: 'LIVE CONCERT', venueEn: 'KBS Arena', locationEn: 'Seoul, Korea',
    production: 'FIG',
    role: 'Show Direction · Creative Direction · Project Management',
    desc: '대한민국 대표 크리에이터들과 함께하는 축제, 유튜브 팬페스트 코리아',
    tasks: ['프로그램 및 공연 구성 총괄', '현장 리허설 및 쇼 플로우 총괄', '출연진 및 파트너 커뮤니케이션', '운영 계획 및 관계자, 협력사 커뮤니케이션', '행사 정산 및 예산 관리'],
    image: 'https://storage.googleapis.com/gweb-uniblog-publish-prod/original_images/YouTube_Fanfest_2025.png',
  },

  {
    company: 'FIG', companyLabel: 'FIG', year: 2024,
    title: 'dingo music concert 〈Killing Voice〉',
    client: 'MAKEUS · FIG',
    category: 'LIVE CONCERT', venueEn: 'Olympic Park Handball Gymnasium', locationEn: 'Seoul, Korea',
    role: 'Show Direction · Creative Direction · Project Management',
    desc: '디지털 음악 콘텐츠를 대형 라이브 무대와 관객 참여로 확장한 첫번째 라이브 이벤트',
    tasks: ['공연 컨셉 개발 및 기획 총괄', '프로그램 및 공연 구성 총괄', '출연진 섭외 및 공연 프로그램 기획', '현장 리허설 및 쇼 플로우 총괄', '운영 계획 및 관계자, 협력사 커뮤니케이션'],
    localImage: 'images/projects/2024-killing-voice.gif',
    image: 'https://cdnweb01.wikitree.co.kr/webdata/editor/202407/31/202407311513165603.jpg',
  },

  {
    company: 'FIG', companyLabel: 'FIG', year: 2024,
    title: "HILLSTATE X IPRF'24",
    client: 'Hyundai E&C (HILLSTATE) · FIG',
    category: 'BRAND EXPERIENCE', venueEn: 'Incheon Pentaport Rock Festival', locationEn: 'Incheon, Korea',
    role: 'Creative Direction · Project Management',
    desc: '국내 건설사 최초로 페스티벌 스폰서가 되어 다채로운 구성의 부스와 프로그램 운영',
    tasks: ['컨셉 개발 및 기획 총괄', '공간 디자인 및 제작, 설치 총괄', '운영 계획 및 관계자, 협력사 커뮤니케이션', '행사 정산 및 예산 관리'],
    image: 'https://www1.hdec.kr/FileContents/NewsWideImage/20240812/86032017497899008.jpg',
  },

  {
    company: 'FIG', companyLabel: 'FIG', year: 2024,
    title: '더 뷰티풀 The Beautiful',
    client: 'BTC Communication',
    category: 'LIVE CONCERT', venueEn: 'INSPIRE Arena', locationEn: 'Incheon, Korea',
    role: 'Creative Direction · Project Management',
    desc: '음악과 무대, 관객을 대형 아레나 스케일로 연결한 공연 프로젝트',
    tasks: ['공연 콘텐츠 기획 및 출연진 섭외'],
    localImage: 'images/projects/2024-the-beautiful.jpg',
    image: 'https://www.ddanzi.com/./files/attach/images/977701/340/884/804/be987c728fc663b80ad9a087a7a6fe2c.PNG',
  },

  {
    company: 'FIG', companyLabel: 'FIG', year: 2024,
    title: 'adidas Equipment: Forever Pioneering the Original 〈The Sound Unseen〉',
    client: 'ADIDAS Confirmed · FIG',
    category: 'LIVE EXPERIENCE / BRAND EXPERIENCE', venueEn: 'Layer 41', locationEn: 'Seoul, Korea',
    role: 'Show Direction · Creative Direction · Project Management',
    desc: '아디다스 EQT의 헤리티지를 사운드·AV 퍼포먼스·공간으로 재해석한 브랜드 프로젝트',
    tasks: ['컨셉 개발 및 기획 총괄', '프로그램 및 공연 구성 총괄', '출연진 섭외 및 공연 프로그램 기획', '출연진 및 파트너 커뮤니케이션', '현장 리허설 및 쇼 플로우 총괄', '공간 디자인 및 제작, 설치 총괄', '운영 계획 및 관계자, 협력사 커뮤니케이션', '행사 정산 및 예산 관리'],
    localImage: 'images/projects/2024-adidas-eqt.png',
  },

  {
    company: 'FIG', companyLabel: 'FIG', year: 2024,
    title: 'PODO Private Residence Seoul by FENDI Casa Launching Show',
    client: 'Golden Tree · FIG',
    category: 'VIP EVENT', venueEn: 'The Shilla Seoul', locationEn: 'Seoul, Korea',
    role: 'Show Direction · Creative Direction · Project Management',
    desc: '아시아 최초 FENDI Casa 하이엔드 레지던스 서울 론칭 기념 VIP 이벤트',
    tasks: ['컨셉 개발 및 기획 총괄', '프로그램 및 공연 구성 총괄', '출연진 섭외 및 공연 프로그램 기획', '출연진 및 파트너 커뮤니케이션', '현장 리허설 및 쇼 플로우 총괄', '공간 디자인 및 제작, 설치 총괄', '운영 계획 및 관계자, 협력사 커뮤니케이션', '행사 정산 및 예산 관리'],
    localImage: 'images/projects/2024-podo-fendi-casa.jpg',
    image: 'https://cdn.forbeskorea.co.kr/news/photo/202405/20240525_1_339793.jpg',
  },

  {
    company: 'FIG', companyLabel: 'FIG', year: 2024,
    title: '원티드랩 컬처 프로젝트 〈2024 WANTED OFFROAD STATION〉',
    client: 'WANTED · FIG',
    category: 'CONFERENCE / BRAND EXPERIENCE', venueEn: 'Peaches. D8NE', locationEn: 'Seoul, Korea',
    role: 'Creative Direction · Project Management',
    desc: '강연과 문화 프로그램을 결합해 브랜드와 커뮤니티의 접점을 만든 컬처 프로젝트',
    tasks: ['컨셉 개발 및 기획 총괄', '프로그램 및 구성 총괄', '출연진 섭외 및 프로그램 기획', '출연진 및 파트너 커뮤니케이션', '현장 리허설 및 쇼 플로우 총괄', '공간 디자인 및 제작, 설치 총괄', '운영 계획 및 관계자, 협력사 커뮤니케이션', '행사 정산 및 예산 관리'],
    localImage: 'images/projects/2024-wanted-offroad.jpg',
    image: 'https://static.wanted.co.kr/events/offroadstation2024/og_image.png',
  },

  {
    company: 'FIG', companyLabel: 'FIG', year: 2023,
    title: 'Club ARC with Antenna',
    client: 'LG Arts Center Seoul × Antenna Music · FIG',
    category: 'LIVE EXPERIENCE', venueEn: 'LG Arts Center Seoul', locationEn: 'Seoul, Korea',
    role: 'Show Direction · Creative Direction · Project Management',
    desc: 'LG아트센터와 안테나뮤직의 협업을 전시와 라이브로 구현한 이머시브 공연 시리즈',
    tasks: ['컨셉 개발 및 기획 총괄', '공연 및 전시 프로그램 구성 총괄', '출연진별 컨셉 및 프로그램 기획', '출연진 및 파트너 커뮤니케이션', '현장 리허설 및 쇼 플로우 총괄', '공간 디자인 및 제작, 설치 총괄', '운영 계획 및 관계자, 협력사 커뮤니케이션', '행사 정산 및 예산 관리'],
    image: 'https://www.lgart.com/Down/Perf/202310/03.%ED%81%B4%EB%9F%BD%EC%95%84%ED%81%AC_%EC%99%93%EC%B8%A0%EC%98%A8_%EB%B0%B0%EB%84%88_1025.png',
  },

  {
    company: 'FIG', companyLabel: 'FIG', year: 2023,
    title: 'Hanwha LIFEPLUS × Refik Anadol 〈Machine Simulations: Life and Dreams - 희로애락〉 Opening Event',
    client: 'INNOCEAN · FIG',
    category: 'OFFICIAL CEREMONY / VIP EVENT', venueEn: '63 Building', locationEn: 'Seoul, Korea',
    role: 'Creative Direction · Project Management',
    desc: 'Refik Anadol의 미디어아트 작품 오프닝을 기념하는 프리뷰 프로젝트와 VIP 프로그램',
    tasks: ['컨셉 개발 및 기획 총괄', '공연 및 전시 프로그램 구성 총괄', '출연진 및 파트너 커뮤니케이션', '현장 리허설 및 쇼 플로우 총괄', '공간 디자인 및 제작, 설치 총괄', '운영 계획 및 관계자, 협력사 커뮤니케이션', '행사 정산 및 예산 관리'],
    localImage: 'images/projects/2023-hanwha-lifeplus.jpg',
    image: 'https://www.koreaittimes.com/news/thumbnail/202310/125512_73641_3348_v150.jpg',
  },

  {
    company: 'FIG', companyLabel: 'FIG', year: 2023,
    title: 'dingo 오프라인 BI 리뉴얼',
    client: 'MAKEUS · FIG',
    category: 'IP DEVELOPMENT', venueEn: 'Undisclosed', locationEn: 'Seoul, Korea',
    role: 'Creative Direction · Project Management',
    desc: '딩고의 오프라인 IP 확장을 위한 BI와 전용 시각 언어를 구축한 브랜드 리뉴얼',
    tasks: ['브랜딩 컨셉 개발', 'BI 개발 및 가이드라인 제작 총괄'],
  },

  {
    company: 'FIG', companyLabel: 'FIG', year: 2022,
    title: 'CJ NIGHT for FRIEZE SEOUL 2022',
    client: 'CJ · FIG',
    category: 'VIP EVENT', venueEn: 'Leeum Museum of Art', locationEn: 'Seoul, Korea',
    role: 'Creative Direction · Project Management',
    desc: 'Frieze Seoul 기간 문화·예술 네트워크를 위한 프라이빗 나이트',
    tasks: [],
    localImage: 'images/projects/2022-cj-night-frieze.png',
    image: 'http://img.tf.co.kr/article/home/2022/09/01/202211141662034358.jpg',
  },

  {
    company: 'FIG', companyLabel: 'FIG', year: 2022,
    title: '언더시티 프로젝트 2022',
    client: 'Bupyeong Cultural Foundation',
    category: 'FESTIVAL', venueEn: 'Bupyeong Art Center', locationEn: 'Incheon, Korea',
    role: 'Creative Direction · Project Management',
    desc: '로컬 콘텐츠와 공간을 결합한 도시형 페스티벌',
    tasks: [],
    image: 'https://cdn.incheontoday.com/news/photo/202209/221049_225151_562.jpg',
  },

  {
    company: 'FIG', companyLabel: 'FIG', year: 2021,
    title: '2021 P4G 서울 녹색미래 정상회의 개회식',
    client: 'P4G Seoul Summit Preparatory Office · ezPMP',
    category: 'OFFICIAL CEREMONY', venueEn: 'DDP', locationEn: 'Seoul, Korea',
    role: 'Creative Planning · Content Producing',
    desc: '기후 의제를 정상회의의 메시지·영상·하이브리드 운영으로 전달한 국제행사 개회식',
    tasks: [],
    image: 'https://www.hanwha.com/content/dam/hanwha/news_and_media/hanwha-insight/hanwha-outlines-path-for-measurable-progress-against-climate-change-at-2021-p4g-seoul-summit/p4g_seoul_summit_1.jpg',
  },

  {
    company: 'FIG', companyLabel: 'FIG', year: 2019,
    title: '2019년 한·아세안 특별정상회의 기념 콘서트 〈ASEAN Fantasia〉',
    client: 'Ministry of Culture, Sports and Tourism · Korean Foundation for International Cultural Exchange',
    category: 'LIVE CONCERT', venueEn: 'Changwon Indoor Gymnasium', locationEn: 'Changwon, Korea',
    role: 'Show Direction · Creative Direction · Project Management',
    desc: '한-아세안 특별정상회의의 문화적 결합을 K-팝 콘서트로 전하는 전야 콘서트',
    tasks: [],
    image: 'https://img5.yna.co.kr/etc/inner/EN/2019/11/14/AEN20191114004600315_01_i_P4.jpg',
  },

  {
    company: 'FIG', companyLabel: 'FIG', year: 2019,
    title: '한-아세안 특별정상회의 환영만찬 문화공연',
    client: 'Ministry of Foreign Affairs',
    category: 'OFFICIAL CEREMONY', venueEn: 'Ananti Hotel', locationEn: 'Busan, Korea',
    role: 'Show Direction · Creative Direction, Content Produce',
    desc: '한-아세안 특별정상회의 정산 만찬 기념 공연',
    tasks: [],
    localImage: 'images/projects/2019-korea-asean-gala.jpg',
  },

  {
    company: 'FIG', companyLabel: 'FIG', year: 2019,
    title: '판문점선언 1주년 기념 평화 공연 〈먼, 길〉',
    client: 'Ministry of Unification',
    category: 'LIVE CONCERT', venueEn: 'Panmunjom', locationEn: 'Korea',
    role: 'Show Direction · Creative Direction',
    desc: '판문점선언 1주년의 의미를 공연과 기념 프로그램으로 전달한 문화행사',
    tasks: [],
    localImage: 'images/projects/2019-long-road.jpg',
    image: 'https://img.sbs.co.kr/newimg/news/20190427/201307653_1280.jpg',
  },

  {
    company: 'NBNDR', companyLabel: 'NBNDR', year: 2018,
    title: "'사랑을 했다' 여름 피크닉 〈PiKONICDAY〉",
    client: 'YG ENTERTAINMENT',
    category: 'LIVE EVENT', venueEn: '반포 한강공원 예빛섬', locationEn: 'Seoul, Korea',
    role: 'Creative Direction, Project Management',
    desc: 'iKON 퍼블릭 팬 이벤트(체험, 전시, 퍼포먼스 진행)',
    tasks: [],
    localImage: 'images/projects/2018-pikonicday.jpg',
    image: 'https://yg-life.com/wp-content/uploads/2018/07/91a66859b84bd72d23d66fe5a4fa0c8f-e1532510188328.jpg',
  },

  {
    company: 'NBNDR', companyLabel: 'NBNDR', year: 2018,
    title: 'MAMF 2015~2018',
    displayYear: '2015-2018',
    client: 'Gyeongnam Migrant Workers Center',
    category: 'FESTIVAL', venueEn: 'Yongji Cultural Park, Seongsan Art Hall', locationEn: 'Changwon, Korea',
    role: 'Show Direction · Creative Direction',
    desc: '창원에서 열리는 대한민국 대표 문화다양성 축제',
    tasks: [],
    image: 'https://philembassy-seoul.com/storage/articles/announcement/2018917_MAMF.jpg',
  },

];
